CREATE TABLE raw.team_stats (
    year                              INT,
    team                              TEXT,
    conference                        TEXT,
    games                             INT,
    total_yards                       NUMERIC,
    net_passing_yards                 NUMERIC,
    rushing_yards                     NUMERIC,
    pass_attempts                     INT,
    pass_completions                  INT,
    passing_tds                       INT,
    rushing_attempts                  INT,
    rushing_tds                       INT,
    first_downs                       INT,
    third_downs                       INT,
    third_down_conversions            INT,
    fourth_downs                      INT,
    fourth_down_conversions           INT,
    kick_return_yards                 NUMERIC,
    kick_returns                      INT,
    kick_return_tds                   INT,
    punt_return_yards                 NUMERIC,
    punt_returns                      INT,
    punt_return_tds                   INT,
    possession_time                   NUMERIC,
    penalties                         INT,
    penalty_yards                     NUMERIC,
    fumbles_lost                      INT,
    fumbles_recovered                 INT,
    interceptions                     INT,
    interception_yards                NUMERIC,
    interception_tds                  INT,
    total_yards_opponent              NUMERIC,
    net_passing_yards_opponent        NUMERIC,
    rushing_yards_opponent            NUMERIC,
    pass_attempts_opponent            INT,
    pass_completions_opponent         INT,
    passing_tds_opponent              INT,
    rushing_attempts_opponent         INT,
    rushing_tds_opponent              INT,
    first_downs_opponent              INT,
    third_downs_opponent              INT,
    third_down_conversions_opponent   INT,
    fourth_downs_opponent             INT,
    fourth_down_conversions_opponent  INT,
    sacks                             INT,
    sacks_opponent                    INT,
    tackles_for_loss                  INT,
    tackles_for_loss_opponent         INT,
    turnovers                         INT,
    turnovers_opponent                INT,
    passes_intercepted                INT,
    passes_intercepted_opponent       INT,
    fumbles_recovered_opponent        INT,
    penalties_opponent                INT,
    penalty_yards_opponent            NUMERIC,
    possession_time_opponent          NUMERIC,
    _ingested_at                      TIMESTAMP DEFAULT NOW(),
    PRIMARY KEY (year, team)
);

CREATE TABLE raw.advanced_stats (
    year                              INT,
    team                              TEXT,
    conference                        TEXT,
    off_plays                         INT,
    off_drives                        INT,
    off_ppa                           NUMERIC(10,6),
    off_total_ppa                     NUMERIC(10,4),
    off_success_rate                  NUMERIC(10,6),
    off_explosiveness                 NUMERIC(10,6),
    off_power_success                 NUMERIC(10,6),
    off_stuff_rate                    NUMERIC(10,6),
    off_line_yards                    NUMERIC(10,4),
    off_second_level_yards            NUMERIC(10,4),
    off_open_field_yards              NUMERIC(10,4),
    off_points_per_opportunity        NUMERIC(10,4),
    off_field_position_avg_start      NUMERIC(6,2),
    off_field_position_predicted_pts  NUMERIC(10,4),
    off_havoc_total                   NUMERIC(6,4),
    off_havoc_front_seven             NUMERIC(6,4),
    off_havoc_db                      NUMERIC(6,4),
    off_std_downs_rate                NUMERIC(10,6),
    off_std_downs_ppa                 NUMERIC(10,6),
    off_std_downs_success_rate        NUMERIC(10,6),
    off_std_downs_explosiveness       NUMERIC(10,6),
    off_pass_downs_rate               NUMERIC(10,6),
    off_pass_downs_ppa                NUMERIC(10,6),
    off_pass_downs_success_rate       NUMERIC(10,6),
    off_pass_downs_explosiveness      NUMERIC(10,6),
    off_rushing_rate                  NUMERIC(10,6),
    off_rushing_ppa                   NUMERIC(10,6),
    off_rushing_success_rate          NUMERIC(10,6),
    off_rushing_explosiveness         NUMERIC(10,6),
    off_passing_rate                  NUMERIC(10,6),
    off_passing_ppa                   NUMERIC(10,6),
    off_passing_success_rate          NUMERIC(10,6),
    off_passing_explosiveness         NUMERIC(10,6),
    def_plays                         INT,
    def_drives                        INT,
    def_ppa                           NUMERIC(10,6),
    def_total_ppa                     NUMERIC(10,4),
    def_success_rate                  NUMERIC(10,6),
    def_explosiveness                 NUMERIC(10,6),
    def_power_success                 NUMERIC(10,6),
    def_stuff_rate                    NUMERIC(10,6),
    def_line_yards                    NUMERIC(10,4),
    def_second_level_yards            NUMERIC(10,4),
    def_open_field_yards              NUMERIC(10,4),
    def_points_per_opportunity        NUMERIC(10,4),
    def_field_position_avg_start      NUMERIC(6,2),
    def_field_position_predicted_pts  NUMERIC(10,4),
    def_havoc_total                   NUMERIC(6,4),
    def_havoc_front_seven             NUMERIC(6,4),
    def_havoc_db                      NUMERIC(6,4),
    def_std_downs_rate                NUMERIC(10,6),
    def_std_downs_ppa                 NUMERIC(10,6),
    def_std_downs_success_rate        NUMERIC(10,6),
    def_std_downs_explosiveness       NUMERIC(10,6),
    def_pass_downs_rate               NUMERIC(10,6),
    def_pass_downs_ppa                NUMERIC(10,6),
    def_pass_downs_success_rate       NUMERIC(10,6),
    def_pass_downs_explosiveness      NUMERIC(10,6),
    def_rushing_rate                  NUMERIC(10,6),
    def_rushing_ppa                   NUMERIC(10,6),
    def_rushing_success_rate          NUMERIC(10,6),
    def_rushing_explosiveness         NUMERIC(10,6),
    def_passing_rate                  NUMERIC(10,6),
    def_passing_ppa                   NUMERIC(10,6),
    def_passing_success_rate          NUMERIC(10,6),
    def_passing_explosiveness         NUMERIC(10,6),
    _ingested_at                      TIMESTAMP DEFAULT NOW(),
    PRIMARY KEY (year, team)
);

CREATE TABLE raw.plays (
    id                 TEXT PRIMARY KEY,
    game_id            BIGINT,
    drive_id           TEXT,
    drive_number       INT,
    play_number        INT,
    season             INT,
    week               INT,
    season_type        TEXT,
    offense            TEXT,
    offense_conference TEXT,
    defense            TEXT,
    defense_conference TEXT,
    home               TEXT,
    away               TEXT,
    offense_score      INT,
    defense_score      INT,
    period             INT,
    clock_minutes      INT,
    clock_seconds      INT,
    yard_line          INT,
    yards_to_goal      INT,
    down               INT,
    distance           INT,
    yards_gained       INT,
    scoring            BOOLEAN,
    play_type          TEXT,
    play_text          TEXT,
    ppa                NUMERIC(10,6),
    wallclock          TEXT,
    _ingested_at       TIMESTAMP DEFAULT NOW()
);

CREATE INDEX idx_plays_game_id   ON raw.plays (game_id);
CREATE INDEX idx_plays_season    ON raw.plays (season);
CREATE INDEX idx_plays_offense   ON raw.plays (offense);
CREATE INDEX idx_plays_defense   ON raw.plays (defense);
CREATE INDEX idx_plays_play_type ON raw.plays (play_type);
